juntabiosGit/appDevThursday

activity1.java
=> Added name: palatan

activity1.java
=> PAUL VINCENT MAHINAY

activity1.java
=> Xialeemar Bautista

activity1.java
=> Carl Vincent Banas

activity1.java
=> Added name: Jay Jay Clapis

activity1.java
=> MARK VINCENT CERZO

activity1.java
=> Kimberly Allosada

activity1.java
=> Carlo Gejos

activity1.java
=> Raquino,Michaela Angel

activity1.java
=> Angel Mae Valdez

activity1.java
=> JUZTINE ABIJAH P. REYES

activity1.java
Added my name Treselle Anne P. Granado
=> activity1.java

activity1.java
=> JOHN CEDRIC DOLOM

activity1.java
added name my  Angelica Batuigas
=> Update Batuigas activity1.java

Activity 1
git add Activity1.java
git commit -m "Added name: Don Edward"
git push origin Lopez
=> Activity 1 Java

activity1.java
git add Activity1.java
git commit -m "Added name: Don Edward"
git push origin Lopez
=> git checkout -b <lopez>

Lopez.Java
git add .
git commit -m "Added Lopez.java"
git push origin main
=> Lopez.Java

Piano.java, week4.java
Added Piano.java and Modified Week4.java
=> Week4 Activity

KPClark.java, week4.java
Kleine Paul Clark from BSIT-2L, adding my first name initials to avoid confusion of having 2 identical Clark commits.
=> Added KPClark.java

Gollena.java, week4.java
=> Gollena.java

Clapis.java, week4.java
Added Clapis.java and modified week4.java.
=> Clapis.java

Granado.java
I have added my Granado.java method to the project.
=> Granado.java

week4.java
I have added my Granado.java method to the project.
=> week4.java

Batuigas.java
=> Batuigas.java

JMasagca.java, week4.java
=> Added JMasagca.java

NMasagca.java, week4.java
=> Added NMasagca.java

Reyes.java, week4.java
Added Reyes.java and edited week4.java
=> Added Reyes.java and week4.java

Gejos.java, week4.java
Added Gejos.java and modified week4.java
=> Gejos.java

week5.java
=> estonilo week5.java

ClarkKurt.java, week5.java
Add ClarkKurt.java with age calculation and updated week5.java
=> Add ClarkKurt.java with age calculation and updated week5.java

week5.java
=> week5.java

Gollena.txt, week5.java
Add Gollena.java with age calculation and updated week5.java
=> Add Gollena.java with age calculation and updated week5.java

NMasagca.java, week5.java
=> Added NMasagca.java with age calculation and updated week5.java

JMasagca.java, week5.java
=> Added JMaasagca.java with age calculation and updated week5.java

ClarkKleine.java, week5.java
YES! kaya pala denied permissions ko prof dahil ang na-clone ko ay yung github mo, imbles na yung username ko. NEWBIE MISTAKE! (╯°□°）╯︵ ┻━┻.
Ngayun ko lang po nasend kase ngayun ko lang na realize, hahaha
=> Added ClarkKleine.java with age calculation and updated week5.java

Lopez.java, week5.java
=> Added Lopez.java with age calculation and updated week5.java

Dolom.java, Gejos.java, week5.java
Added Gejos.java with age calculation and updated week5.java
=> Added Gejos.java with age calculation and updated week5.java

Dolom.java, week5.java
Added Dolom.java with age calculation and updated week5.java
=> Added Dolom.java with age calculation and updated week5.java

Allosada.java, week5.java
Added Allosada.java with age calculation and updated week5.java
=> Allosada.java

Calculator.java, GroupWork.java
Corrected typo error on Comment in Calculator.java
=> Updated files

Calculator.java, GroupWork.java
Implemented modulus method in Calculator.java
=> Group 5: Added modulus method

Calculator.java, GroupWork.java
Group 8: Added max method (Clapis, Bautista, Estonillo, Urmatam, Mahinay, Larioza, Indonilla, Allosada, Banas, Batuigas)
=> Group 8: Added max method

Calculator.java
…-SANTANDER,-HALLIG,-ORDINARIO,-MUYRONG,-ABOHAN,-ANTONIO)
=> Group-6-Added-Square-Method-(Members-JARDELEZA,-SAN-MIGUEL,-GABRILLO,-SANTANDER,-HALLIG,-ORDINARIO,-MUYRONG,-ABOHAN,-ANTONIO)
